### ISSUE TITLE
encrypted field Account.Phone does not support aggregate operator COUN

### ISSUE THREAD

**Issue by sombir-sheoran** [amitastreait/sfdx-data-dictonary#1]
Getting the below error while running the command in my org:

sfdx field:usage -u <username-alais> --object "Account" --path "FieldUsage.xlsx"

Error details:
The total number of records for the Account are 107 
ERROR running field:usage: 
count(ShippingLongitude) ShippingLongitude ,  count(Phone) Phone ,  count(Fax) Fax 
                                                    ^
ERROR at Row:1:Column:531
encrypted field Account. Phone does not support aggregate operator COUNT

![image](https://user-images.githubusercontent.com/25195233/208354784-b65a551c-6d2f-4f9f-b23a-3733a6bdf5f4.png)

**Comment by amitastreait** [comment]
Fixed in the latest version of the plugin
